### ISSUE TITLE
[warning] mutating the [[Prototype]] of an object will cause your code to run very slowly

### ISSUE THREAD

**Issue by speciose** [rclai/meteor-collection-extensions#10]
I don't use this package directly (and can't find where it comes from in my system) but I'm always getting this annoying warning in firefox console
```
mutating the [[Prototype]] of an object will cause your code to run very slowly; 
instead create the object with the correct initial [[Prototype]] value using Object.create
```
and peace of code:

![capture11](https://cloud.githubusercontent.com/assets/8721324/8778925/2bbe02b8-2f09-11e5-8cc1-bf3754955e55.PNG)

**Comment by speciose** [comment]
I've found out that it's from mongol package (and I don't need it in production) but anyway. Is this warning ok?

**Comment by rclai** [comment]
This is a common warning that is raised only by Firefox, when replacing the prototype of an object, there's nothing that can be done about it, except not do that, but then the `Meteor.users` collection will not work properly.
