### ISSUE TITLE
zimme:collection-behaviours

### ISSUE THREAD

**Issue by abernix** [rclai/meteor-collection-extensions#9]
I'm not currently using your package, but I intend to in the future.  Real nice work and definitely needed.  

I just ran into [another `collection-behaviors`](https://github.com/zimme/meteor-collection-behaviours/), apparently quickly gaining traction.  Realized it was a different one than the one you had on your list and thought you might want it on your TODO list, at the very least.  I think the zimme package has autoform support which might be the upper hand for it right now.

Anyway, just an FYI ticket. :)

**Comment by rclai** [comment]
Yes. At the time that I wrote this, sewdn's version had more downloads than zimme's so I thought that was the dominant one, but looks like zimme's is more active. I will put it in.

**Comment by zimme** [comment]
I won't be able to use this package until you put it under it's own namespace, won't use a package which adds new functionality under `Meteor` (#2).

I think I could use this package to add `attachBehaviour` to `Mongo.Collection.prototype`.

I think I could also use this package to automatically add behaviours to all collections if a package setting was available on `Meteor.settings`.

I'm currently working on a es2015 re-write of all my packages so this would be a good time to try and use this package.

I think the idea of this package is nobel, but it needs work and I may be able to help with that later on.

**Comment by rclai** [comment]
I will put it on my todos.

**Comment by rclai** [comment]
@zimme, I've deprecated the `Meteor` namespace for the functionality. It's now on the `CollectionExtensions` namespace.

**Comment by rclai** [comment]
Oh wait, hold on, I got the naming wrong.

**Comment by rclai** [comment]
Okay it should be good now.

**Comment by zimme** [comment]
Nice, I'm doing a es2015 rewrite of `zimme:collection-behaviours` will be releasing it under `collectionbehaviours:core` too. I'll switch over to use this package for the `Mongo` adding stuff.
